# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Folder
version:      0.851
version_from: lib/Email/Folder.pm
installdirs:  site
requires:
    Email::FolderType:             0.6
    Email::Simple:                 0
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
