--- #YAML:1.0
name: Email-Folder
version: 0.5
license: perl
distribution_type: module
requires:
  Email::FolderType: 0
  Email::Simple: 0
  Test::More: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Email::Folder:
    file: lib/Email/Folder.pm
    version: 0.5
  Email::Folder::Reader:
    file: lib/Email/Folder/Reader.pm
    version: ~
generated_by: Module::Build version 0.18
