---
name: Email-Folder
version: 0.85
author: ~
abstract: read all the messages from a folder as Email::Simple objects.
license: perl
requires:
  Email::FolderType: 0.6
  Email::Simple: 0
  Test::More: 0
provides:
  Email::Folder:
    file: lib/Email/Folder.pm
    version: 0.85
  Email::Folder::Ezmlm:
    file: lib/Email/Folder/Ezmlm.pm
  Email::Folder::MH:
    file: lib/Email/Folder/MH.pm
  Email::Folder::Maildir:
    file: lib/Email/Folder/Maildir.pm
  Email::Folder::Mbox:
    file: lib/Email/Folder/Mbox.pm
  Email::Folder::Reader:
    file: lib/Email/Folder/Reader.pm
generated_by: Module::Build version 0.2611
